"""MITRE ATT&CK Navigator Layer JSON exporter.

Generates ATT&CK Navigator v4.5 layer JSON from observed techniques, findings,
or policy detections, ready for import into the ATT&CK Navigator web UI.
"""

from __future__ import annotations

import json
from typing import Any

from centralium.agent.models import Finding


def _score_to_color(score: float) -> str:
    """Map a score (0..100) to a heatmap color hex string."""
    if score >= 80:
        return "#ff3333"  # Red (High/Critical)
    if score >= 50:
        return "#ffaa00"  # Orange (Medium)
    if score >= 20:
        return "#ffff66"  # Yellow (Low)
    return "#cccccc"  # Grey (Info)


def export_navigator_layer(
    techniques_or_findings: dict[str, float] | list[str] | list[Finding],
    name: str = "Centralium Threat Detection Coverage",
    description: str = "Automated MITRE ATT&CK detection layer generated by Centralium EDR.",
) -> dict[str, Any]:
    """Build an ATT&CK Navigator layer dict from techniques or findings."""
    tech_map: dict[str, dict[str, Any]] = {}

    if isinstance(techniques_or_findings, dict):
        for tech_id, score in techniques_or_findings.items():
            tech_map[tech_id] = {
                "score": float(score),
                "comments": [f"Score: {score:.1f}"],
            }
    elif isinstance(techniques_or_findings, list):
        for item in techniques_or_findings:
            if isinstance(item, str):
                tech_id = item.strip().upper()
                if tech_id:
                    existing = tech_map.get(tech_id, {"score": 50.0, "comments": []})
                    tech_map[tech_id] = existing
            elif isinstance(item, Finding):
                for tech_id in item.mitre_techniques or []:
                    t_clean = tech_id.strip().upper()
                    if not t_clean:
                        continue
                    current = tech_map.get(t_clean, {"score": 0.0, "comments": []})
                    current["score"] = max(current["score"], float(item.score))
                    current["comments"].append(f"{item.rule_id} ({item.severity})")
                    tech_map[t_clean] = current

    tech_list: list[dict[str, Any]] = []
    for tech_id, data in sorted(tech_map.items()):
        score = data["score"]
        comments = "; ".join(data["comments"][:5])
        tech_list.append(
            {
                "techniqueID": tech_id,
                "score": round(score, 1),
                "color": _score_to_color(score),
                "comment": comments,
                "enabled": True,
            }
        )

    return {
        "name": name,
        "versions": {
            "attack": "14",
            "navigator": "4.5",
            "layer": "4.5",
        },
        "domain": "enterprise-attack",
        "description": description,
        "filters": {
            "platforms": ["Linux", "Windows", "macOS"],
        },
        "sorting": 3,
        "layout": {
            "layout": "side",
            "aggregateFunction": "max",
            "showID": True,
            "showName": True,
        },
        "hideDisabled": False,
        "techniques": tech_list,
        "gradient": {
            "colors": ["#cccccc", "#ffff66", "#ffaa00", "#ff3333"],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [
            {"label": "Critical / High Risk (Score >= 80)", "color": "#ff3333"},
            {"label": "Medium Risk (Score >= 50)", "color": "#ffaa00"},
            {"label": "Low Risk (Score >= 20)", "color": "#ffff66"},
            {"label": "Informational", "color": "#cccccc"},
        ],
    }


def export_navigator_layer_json(
    techniques_or_findings: dict[str, float] | list[str] | list[Finding],
    name: str = "Centralium Threat Detection Coverage",
    indent: int = 2,
) -> str:
    """Export ATT&CK Navigator layer to formatted JSON string."""
    layer = export_navigator_layer(techniques_or_findings, name=name)
    return json.dumps(layer, indent=indent)


__all__ = [
    "export_navigator_layer",
    "export_navigator_layer_json",
]
