#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl stop centralium.service >/dev/null 2>&1 || true
            systemctl disable centralium.service >/dev/null 2>&1 || true
        fi
        ;;
esac

exit 0
